CREATE TABLE "events" (
	"id" SERIAL NOT NULL,
	"eventname" VARCHAR NULL DEFAULT NULL,
	"city" VARCHAR NULL DEFAULT NULL,
	"date" VARCHAR NULL DEFAULT NULL,
	"price" DOUBLE PRECISION NOT NULL DEFAULT E'true',
	"dance" VARCHAR NOT NULL,
	PRIMARY KEY ("id")
)
;
